// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-UPHpYOGhvbTfeC6mIOJvGRFk2chYtg0',
    appId: '1:159899904088:web:61015f290f2018e64f422d',
    messagingSenderId: '159899904088',
    projectId: 'baladi-ca5fb',
    authDomain: 'baladi-ca5fb.firebaseapp.com',
    storageBucket: 'baladi-ca5fb.appspot.com',
    measurementId: 'G-XDFE8EPRGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyHd9ACphjILGc912FFxO7BpV7fhOMyiU',
    appId: '1:159899904088:android:c0fde2b4e38a18254f422d',
    messagingSenderId: '159899904088',
    projectId: 'baladi-ca5fb',
    storageBucket: 'baladi-ca5fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcJnKi5586AO8qbJLDsuzpg_8r_XNDedU',
    appId: '1:159899904088:ios:46a38be9384be1b04f422d',
    messagingSenderId: '159899904088',
    projectId: 'baladi-ca5fb',
    storageBucket: 'baladi-ca5fb.appspot.com',
    iosClientId: '159899904088-u6s0s8djsqfpfrag2alho19krciou5ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharePrefrances',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcJnKi5586AO8qbJLDsuzpg_8r_XNDedU',
    appId: '1:159899904088:ios:46a38be9384be1b04f422d',
    messagingSenderId: '159899904088',
    projectId: 'baladi-ca5fb',
    storageBucket: 'baladi-ca5fb.appspot.com',
    iosClientId: '159899904088-u6s0s8djsqfpfrag2alho19krciou5ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharePrefrances',
  );
}
